backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: public/img
public_folder: img

i18n:
  structure: single_file
  locales: [en, de, de-simple, en-simple]
  default_locale: de

collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    i18n: true
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "date", i18n: duplicate }
      - { label: "Featured Image", name: "thumbnail", widget: "image", i18n: duplicate }
      - { label: "Body", name: "body", widget: "markdown", i18n: true}
  - name: "header_and_footer"
    label: "Header and Footer"
    i18n: true
    format: "json"
    files:
    - file: "content/header.json"
      label: "Header"
      name: "header"
      i18n: true
      fields:
      - {label: "Info", name: "info", widget: "string", i18n: true}
      - {label: "Investors", name: "investors", widget: "string", i18n: true}
      - {label: "Interrested", name: "interested", widget: "string", i18n: true}
      - {label: "Blog", name: "blog", widget: "string", i18n: true}
      - {label: "Telegram", name: "telegram", widget: "string", i18n: true, required: false}
      - {label: "Telegram Tooltip", name: "telegramTooltip", widget: "string", i18n: true}
      - {label: "Brand", name: "brand", widget: "string", i18n: true}
    - file: "content/footer.json"
      label: "Footer"
      name: "footer"
      i18n: true
      fields:
      - {label: "Imprint", name: "imprint", widget: "string", i18n: true}
      - {label: "About", name: "about", widget: "string", i18n: true}
      - {label: "CMS", name: "cms", widget: "string", i18n: true}


  - name: "landing"
    label: "Landing Page"
    i18n: true
    format: "json"
    files:
      - file: "content/contact.json"
        label: "Contact Section"
        name: "contact"
        i18n: true
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true}
          - { label: "Greeting", name: "greeting", widget: "string", i18n: true}
          - { label: "Name", name: "name", widget: "string", i18n: true}
          - { label: "Name Invalid", name: "nameInvalid", widget: "string", i18n: true}
          - { label: "Email", name: "email", widget: "string", i18n: true}
          - { label: "Email Invalid", name: "emailInvalid", widget: "string", i18n: true}
          - { label: "Message", name: "message", widget: "string", i18n: true}
          - { label: "Message Invalid", name: "messageInvalid", widget: "string", i18n: true}
          - { label: "Send Button", name: "send", widget: "string", i18n: true}
      - file: "content/hero.json"
        label: "Hero"
        name: "hero"
        i18n: true
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true}
          - { label: "Subtitle", name: "subtitle", widget: "string", i18n: true }
          - { label: "Image", name: "image", widget: "image", i18n: true }
          - { label: "Image Alt Text", name: "altText", widget: "string", i18n: true }
          - { label: "Contact Button Text", name: "contactButton", widget: "string", i18n: true}
      - file: "content/landing.json"
        label: "Landing Content"
        name: "landing-content"
        i18n: true
        fields:
          - name: "items"
            widget: "list"
            identifier_field: "content"
            i18n: true
            fields:
              - label: "Content"
                name: "content"
                widget: "object"
                fields:
                  - { name: "headline", widget: "string" , i18n: true}
                  - { name: "image-alt", title: "Image Alt Text", widget: "string" , i18n: true}
                  - {
                    name: "image",
                    widget: "image",
                    allow_multiple: false, i18n: true
                  }
                  - { name: "text", widget: "markdown" , i18n: true}
  - name: "imprint"
    label: "Impressum"
    i18n: true
    files:
      - file: "content/imprint.json"
        label: "Impressum"
        name: "imprint"
        i18n: true
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true }
          - { label: "Name", name: "organizationName", widget: "string", i18n: true }
          - { label: "Anschrift", name: "organizationAddress", widget: "markdown", i18n: true }
          - { label: "Email", name: "email", widget: "string", i18n: true }
          - { label: "Hintergrund Bild", name: "backgroundImage", widget: "image", i18n: true }