backend:
  name: git-gateway
local_backend: true
media_folder: public/img
public_folder: img
collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "landing"
    label: "Landing Page"
    files:
      - file: "content/landing.json"
        label: "Landing"
        name: "landing"
        create: "true"
        widget: "list"
        fields:
          - { label: "Quote", name: "quote", widget: "string", default: "Everything is awesome!" }
          - label: "Author"
            name: "author"
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Avatar", name: "avatar", widget: "image" }

      - file: "content/hero.json"
        label: "Hero"
        name: "hero"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Ssubtitle", name: "ssubtitle", widget: "string" }

      - file: "content/landingContent.json"
        label: "Landing Content"
        name: "landing-content"
        format: "json"
        fields:
          - name: "items"
            widget: "list"
            identifier_field: "content"
            fields:
              - label: "Content"
                name: "content"
                widget: "object"
                fields:
                  - { name: "headline", widget: "string" }
                  - {
                    name: "image",
                    widget: "image",
                    allow_multiple: false,
                  }
                  - { name: "text", widget: "text" }