backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: public/img
public_folder: img
collections:
  - name: "landing"
    label: "Landing Page"
    files:

      - file: "content/blogEntries.json"
        label: "Hero"
        name: "hero"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Subtitle", name: "subtitle", widget: "string" }
      - file: "content/hero.json"
        label: "Hero"
        name: "hero"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Subtitle", name: "subtitle", widget: "string" }

      - file: "content/landingContent.json"
        label: "Landing Content"
        name: "landing-content"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"

          - label: "Content"
            name: "content"
            widget: "object"
            fields:
              - { name: "headline", widget: "string" }
              - {
                name: "image",
                widget: "image",
                allow_multiple: false,
              }
              - { name: "text", widget: "text" }