backend:
  name: git-gateway
  branch: master
media_folder: assets/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Hero"
        name: "hero"
        file: "content/hero.md"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Subtitle", name: "subtitle", widget: "string" }