backend:
  name: git-gateway
local_backend: true
media_folder: public/img
public_folder: img
collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "landing"
    label: "Landing Page"
    files:
      - file: "content/imprint.json"
        label: "Impressum"
        name: "imprint"
        fields:
          - { label: "Name", name: "organizationName", widget: "string"}
          - { label: "Anschrift", name: "organizationAddress", widget: "markdown"}
          - { label: "Email", name: "email", widget: "string"}
          - { label: "Hintergrund Bild", name: "backgroundImage", widget: "image"}

      - file: "content/hero.json"
        label: "Hero"
        name: "hero"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Ssubtitle", name: "ssubtitle", widget: "string" }

      - file: "content/landingContent.json"
        label: "Landing Content"
        name: "landing-content"
        format: "json"
        fields:
          - name: "items"
            widget: "list"
            identifier_field: "content"
            fields:
              - label: "Content"
                name: "content"
                widget: "object"
                fields:
                  - { name: "headline", widget: "string" }
                  - { name: "image-alt", title: "Image Alt Text", widget: "string" }
                  - {
                    name: "image",
                    widget: "image",
                    allow_multiple: false,
                  }
                  - { name: "text", widget: "markdown" }